"""initial_schema

Revision ID: 4b029898fcf0
Revises: 
Create Date: 2026-05-16 23:30:18.395704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b029898fcf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('comun', 'lab_computo', 'lab_redes', 'lab_bd', 'lab_ia', 'lab_software', 'auditorio', name='tipoaulaenum'), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escuelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('es_electivo', sa.Boolean(), nullable=False),
    sa.Column('horas_T', sa.Integer(), nullable=False),
    sa.Column('horas_P', sa.Integer(), nullable=False),
    sa.Column('horas_L', sa.Integer(), nullable=False),
    sa.Column('tipo_lab_requerido', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('nombrado', 'contratado', name='tipodocenteenum'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('regimen', sa.Enum('DE', 'TC', 'TP1', 'TP2', 'TP3', 'CONTRATO_A1', 'CONTRATO_A2', 'CONTRATO_A3', 'CONTRATO_B1', 'CONTRATO_B2', 'CONTRATO_B3', name='regimenenum'), nullable=False),
    sa.Column('categoria', sa.Enum('principal', 'asociado', 'auxiliar', name='categoriaenum'), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('configurando', 'asignando', 'generando', 'publicado', name='estadosemestreenum'), nullable=False),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('docente_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente_disponibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('LUN', 'MAR', 'MIE', 'JUE', 'VIE', name='diaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente_preferencias',
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('turno_preferido', sa.Enum('manana', 'tarde', 'indiferente', name='turnoenum'), nullable=False),
    sa.Column('max_horas_seguidas', sa.Integer(), nullable=False),
    sa.Column('dias_evitar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('docente_id')
    )
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('letra', sa.String(length=2), nullable=False),
    sa.Column('num_alumnos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semestre_aulas_disponibles',
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('semestre_id', 'aula_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'director_escuela', 'director_depto', 'docente', name='roleenum'), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grupos_lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('num_alumnos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('componentes_a_programar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('T', 'P', 'L', name='tipocomponenteenum'), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('grupo_lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['grupo_lab_id'], ['grupos_lab.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario_bloques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('LUN', 'MAR', 'MIE', 'JUE', 'VIE', name='diaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['componente_id'], ['componentes_a_programar.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario_bloques')
    op.drop_table('componentes_a_programar')
    op.drop_table('grupos_lab')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('semestre_aulas_disponibles')
    op.drop_table('secciones')
    op.drop_table('docente_preferencias')
    op.drop_table('docente_disponibilidad')
    op.drop_table('docente_cargos')
    op.drop_table('semestres')
    op.drop_table('docentes')
    op.drop_table('cursos')
    op.drop_table('escuelas')
    op.drop_table('departamentos')
    op.drop_table('facultades')
    op.drop_table('aulas')
    # ### end Alembic commands ###
